# RVLInventory aka MMOInventory
# Dev STABLE Version

update-notify: true

# Automatically saves player data at a set interval.
# Reload required when edited
auto-save:
  enabled: true
  interval: 1800 # In seconds (1800 = 30 minutes)
  log: true

# Will verbose to the console whenever
# data is saved/loaded from the SQL database.
debug: false

############################
# MySQL Support            #
# NOTICE: Removed by Blub  #
# DO NOT USE THIS          #
############################
mysql:
  enabled: false
  host: localhost
  port: 3306
  database: minecraft
  user: mmolover
  pass: ILoveAria
  properties:
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
############################

# Amount of slots in the inventory - has to be a multiple of 9.
# Remember to update the slot numbers in items.yml after changing this option.
inventory-slots: 36

# Enable this option to move the accessory slots to the player
# inventory. A tutorial is available on the resource page.
# Requires a server reload when changed.
no-custom-inventory: false

# This prevents a known dupe bug so it is strongly
# recommended to keep this set to true.
disable-equiping-stacked-items: true

# Items will drop (when keep-inventory is disabled) on death.
# Requires a server reload when changed.
drop-on-death: false

# Available modules:
# - aureliumskills (level only)
# - battlelevels (level only)
# - default (uses player's exp bar, level only)
# - heroes
# - mcmmo (level only)
# - mcrpg (level only)
# - mmocore
# - proskillapi
# - racesandclasses
# - rpgplayerleveling (level only)
# - skillapi
# - skills
# - skillspro
# - asakarvlskills (level only)
level-module: mmocore # default
class-module: mmocore # default

# Adds a static to the player's inventory.
# Opens up the custom inventory when clicked.
# Requires a server reload when changed.
inventory-button:
  enabled: false
  slot: 9
  item:
    material: CHEST
    name: '&6Custom Inventory'
    lore:
      - ''
      - '&eClick to open.'
    # custom-model-data: 1
    # skull-texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjg5Yjk4ZjA0YzMyMjdkMzdkMzE5YmJjZmZjNTFmNTJlNzhkOTZhMDViMTI4NTJkMWI0NjRiYjc0MDhhNzgxMCJ9fX0=

# Enable/disable auto resource pack download. Requires a server reload when changed.
# Default RP: https://www.dropbox.com/s/1lftxmzh0q4b5yu/mmoinv_rp_3.zip?dl=1
resource-pack:
  enabled: false
  url: resource_pack_url
  delay: 20

  # Kick player if he does not accept the server resource pack or
  # if the download failed. Requires a server reload when changed.
  kick:
    enabled: false
    message: 'Vùi lòng tải resourcepack của máy chủ trước khi chơi!'